config/routes.rb
Rails.application.routes.draw do
  resources :stripe_payments
  post '/payment/charge', to: 'stripe_payments#pay', as: 'stripe_paymentgateway' #stripe payment routes
  
  root to: "stripe_payments#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stripe_payment.rb
# == Schema Information
#
# Table name: stripe_payments
#
#  id          :integer          not null, primary key
#  customer_id :decimal(, )
#  amount      :string
#  status      :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  response    :text
#
class StripePayment < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/stripe_payments_controller.rb
class StripePaymentsController < ApplicationController
  before_action :set_stripe_payment, only: %i[ show edit update destroy ]
  skip_before_action :verify_authenticity_token, only: [:pay]

  require 'stripe'
  require 'json'

  # GET /stripe_payments or /stripe_payments.json
  def index
    @stripe_payments = StripePayment.all
  end

  #pay using stripe_payment gateway
  def pay
      Stripe.api_key = 'sk_test_51Jyt87SG0QTZvhDzd8HfZOQ5oU4dFlUzo2M6rLdr95eA10KEKiGnfJzs5PyAfs5QmvzTEQ0h3UvLgx7vXfa6eaKN00dBqNR3Bd'
      customer = Stripe::Customer.create(
              :email => 'bablu@gmaiil.com',
              :card  => params[:stripeToken]
              )
    
      response_data= Stripe::Charge.create({
        customer: customer.id,
        amount: params[:amount],#4000,#amount
        currency: 'inr',
        description: 'Payments test from rails test application',
        :metadata => {
          "Wallet_id" => params[:wallet_id]
        },
      "shipping": {
        "address": {
          "city" => "Chandigarh",
          "country" => "IN",
          "line1" => "Deepcomplex Chandigarh",
          "line2" => "Chandigarh",
          "postal_code" => "160002",
          "state" => "CHD"
        },
        "name": 'bablu',
        "phone": "8451515165"
    },
      })
      if response_data.status == 'succeeded'
        # redirect_url='here'
        charge_data = Stripe::Charge.retrieve(response_data.id,)
        StripePayment.create status: response_data.status, response: charge_data ,amount: response_data.amount/100,customer_id: customer.id

        respond_to do |format|
          format.html { redirect_to stripe_payments_url, notice: "Stripe payment was successfully paid." }
        end
      else
        respond_to do |format|
          format.html { redirect_to stripe_payments_url, notice: "Stripe payment was failed." }
        end
      end
      
  end
  # GET /stripe_payments/1 or /stripe_payments/1.json
  def show
  end

  # GET /stripe_payments/new
  def new
    @stripe_payment = StripePayment.new
  end

  # GET /stripe_payments/1/edit
  def edit
  end

  # POST /stripe_payments or /stripe_payments.json
  def create
    @stripe_payment = StripePayment.new(stripe_payment_params)

    respond_to do |format|
      if @stripe_payment.save
        format.html { redirect_to @stripe_payment, notice: "Stripe payment was successfully created." }
        format.json { render :show, status: :created, location: @stripe_payment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stripe_payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stripe_payments/1 or /stripe_payments/1.json
  def update
    respond_to do |format|
      if @stripe_payment.update(stripe_payment_params)
        format.html { redirect_to @stripe_payment, notice: "Stripe payment was successfully updated." }
        format.json { render :show, status: :ok, location: @stripe_payment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stripe_payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stripe_payments/1 or /stripe_payments/1.json
  def destroy
    @stripe_payment.destroy
    respond_to do |format|
      format.html { redirect_to stripe_payments_url, notice: "Stripe payment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stripe_payment
      @stripe_payment = StripePayment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def stripe_payment_params
      params.require(:stripe_payment).permit(:customer_id, :amount, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stripe_payments_helper.rb
module StripePaymentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImplementStripe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stripe_payments/_form.html.erb
<%= form_with(model: stripe_payment) do |form| %>
  <% if stripe_payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stripe_payment.errors.count, "error") %> prohibited this stripe_payment from being saved:</h2>

      <ul>
        <% stripe_payment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :customer_id %>
    <%= form.text_field :customer_id %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stripe_payments/edit.html.erb
<h1>Editing Stripe Payment</h1>

<%= render 'form', stripe_payment: @stripe_payment %>

<%= link_to 'Show', @stripe_payment %> |
<%= link_to 'Back', stripe_payments_path %>

app/views/stripe_payments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stripe Payments</h1>
<!--
<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>Amount</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stripe_payments.each do |stripe_payment| %>
      <tr>
        <td><%= stripe_payment.customer_id %></td>
        <td><%= stripe_payment.amount %></td>
        <td><%= stripe_payment.status %></td>
        <td><%= link_to 'Show', stripe_payment %></td>
        <td><%= link_to 'Edit', edit_stripe_payment_path(stripe_payment) %></td>
        <td><%= link_to 'Destroy', stripe_payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>-->
<script src="https://js.stripe.com/v3/"></script>

<br>
<form action="/payment/charge" method="post" id="payment-form">
  <div class="form-row">
    
    <div class="wallet_id">
    Wallet_id :<input type="text" name="wallet_id" />
    </div>
  <br />
    <div class="amount">
    Amount :<input type="text" name="amount" />
    </div>
    <br />
    <label for="card-element">
      Credit or debit card
    </label>
    <div id="card-element">
    </div>
   
    <div id="card-errors" role="alert"></div>
  </div>

  <button>Submit Payment</button>
</form>

<br />

<script>
var stripe = Stripe('pk_test_51Jyt87SG0QTZvhDzlqevaI4tWpQMUKWBVFpJFCP1e34wURaB9QIQCZCC620iZxjMGSR6aaalnen14kPC6tdpneTs00T1HmnFde');
var elements = stripe.elements();
var style = {
  base: {
    fontSize: '16px',
    color: '#32325d',
  },
};
var card = elements.create('card', {style: style});
card.mount('#card-element');
var form = document.getElementById('payment-form');
form.addEventListener('submit', function(event) {
  event.preventDefault();

  stripe.createToken(card).then(function(result) {
    if (result.error) {
      var errorElement = document.getElementById('card-errors');
      errorElement.textContent = result.error.message;
    } else {
      stripeTokenHandler(result.token);
    }
  });
});



function stripeTokenHandler(token) {
  var form = document.getElementById('payment-form');
  var hiddenInput = document.createElement('input');
  hiddenInput.setAttribute('type', 'hidden');
  hiddenInput.setAttribute('name', 'stripeToken');
  hiddenInput.setAttribute('value', token.id);
  form.appendChild(hiddenInput);
  form.submit();
}
</script>

<!--<%= link_to 'New Stripe Payment', new_stripe_payment_path %> -->

app/views/stripe_payments/new.html.erb
<h1>New Stripe Payment</h1>

<%= render 'form', stripe_payment: @stripe_payment %>

<%= link_to 'Back', stripe_payments_path %>

app/views/stripe_payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @stripe_payment.customer_id %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @stripe_payment.amount %>
</p>

<p>
  <strong>Status:</strong>
  <%= @stripe_payment.status %>
</p>

<%= link_to 'Edit', edit_stripe_payment_path(@stripe_payment) %> |
<%= link_to 'Back', stripe_payments_path %>